from . import match
from . import games

mvps = {
    'mvp':'mvp',
    'xp': 'experienced',
    'escapes': 'escapeartist',
    'zerg': 'zergcrusher',
    'roots': 'trapper',
    'temple': 'templemaster',
    'skulls': 'skull',
    'gems': 'jeweler',
    'daredevil_escapes': 'daredevil',
    'vengeances': 'avenger',
    'immortal': 'immortalslayer',
    'curse': 'masterofthecurse',
    'dragon': 'shriner',
    'healing': 'mainhealer',
    'silences': 'silencer',
    'stuns': 'stunner',
    'pushing': 'pusher',
    'outnumbered_deaths': 'solesurvivor',
    'hat_trick': 'hattrick',
    'shields': 'protector',
    'siege_damage': 'siegemaster',
    'altar': 'cannoneer',
    'clutch_healing': 'clutchhealer',
    'teamfight_healing': 'combatmedic',
    'hero_damage': 'painbringer',
    'time_on_point': 'pointguard',
    'outnumbered_deaths': 'teamplayer',
    'cage_unlocks': 'wcav',
    'taken_damage': 'bulwark',
    'teamfight_taken_damage': 'guardian',
    'teamfight_hero_damage': 'scrapper',
    'mercs': 'headhunter',
    'kill_streak': 'finisher',
    'seeds': 'gardenterror',
}